// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE6vHnABrd51ZY1OfQR00_hg3BXdLr5Q4',
    appId: '1:31469000998:web:1a9360e03fa913145009e7',
    messagingSenderId: '31469000998',
    projectId: 'todolist-app-d11a5',
    authDomain: 'todolist-app-d11a5.firebaseapp.com',
    storageBucket: 'todolist-app-d11a5.appspot.com',
    measurementId: 'G-09YZ827BDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7JThmyxa1rXqkuxpViIP_sdOwLZ1PSzo',
    appId: '1:31469000998:android:10d81e25282b8b1d5009e7',
    messagingSenderId: '31469000998',
    projectId: 'todolist-app-d11a5',
    storageBucket: 'todolist-app-d11a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwkBwxWB-in3iKgh0zVS_Fy7W2-Dt73CU',
    appId: '1:31469000998:ios:4527edc998d2a4d05009e7',
    messagingSenderId: '31469000998',
    projectId: 'todolist-app-d11a5',
    storageBucket: 'todolist-app-d11a5.appspot.com',
    iosClientId: '31469000998-dj0k1kj0e7b0peb5nivfjl6gcde777ao.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwkBwxWB-in3iKgh0zVS_Fy7W2-Dt73CU',
    appId: '1:31469000998:ios:d371dc4f1cdfb3c15009e7',
    messagingSenderId: '31469000998',
    projectId: 'todolist-app-d11a5',
    storageBucket: 'todolist-app-d11a5.appspot.com',
    iosClientId: '31469000998-1jfi6nqc51io98i5859hv2enlk4s8baf.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListApp.RunnerTests',
  );
}
